### ISSUE TITLE
Error: Route.post() requires callback functions but got a [object Undefined]

### ISSUE THREAD

**Issue by codebreaker01** [meanjs/generator-meanjs#116]
Getting the following error on creating a new crud module. Any ideas how to fix this? Thanks!

```
/Users/jbhambhwani/mobileapi/node_modules/express/lib/router/route.js:160
        throw new Error(msg);
              ^
Error: Route.post() requires callback functions but got a [object Undefined]
    at Route.<anonymous> (/Users/jbhambhwani/mobileapi/node_modules/express/lib/router/route.js:160:15)
    at Array.forEach (native)
    at Route.(anonymous function) [as post] (/Users/jbhambhwani/mobileapi/node_modules/express/lib/router/route.js:156:15)
    at module.exports (/Users/jbhambhwani/mobileapi/app/routes/comments.server.routes.js:10:4)
    at /Users/jbhambhwani/mobileapi/config/express.js:99:35
    at Array.forEach (native)
    at module.exports (/Users/jbhambhwani/mobileapi/config/express.js:98:49)
    at Object.<anonymous> (/Users/jbhambhwani/mobileapi/server.js:24:38)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by codebreaker01** [comment]
Fixed. Had a missing function in one of my routes.

**Comment by OVagner** [comment]
What function was missing? I got the same error and do not know what function is missing.

**Comment by klevamane** [comment]
@OVagner The method or function passed with the route may not exist, for instance a controller class having a method **createuser**, and the route is passed:
router.post('/signup', controllerClass.**registerUser**);
you see that registerUser is not a method of the controller class. With this implementation such error arises. cheers

**Comment by RidhikGovind** [comment]
> @OVagner The method or function passed with the route may not exist, for instance a controller class having a method **createuser**, and the route is passed:
> router.post('/signup', controllerClass.**registerUser**);
> you see that registerUser is not a method of the controller class. With this implementation such error arises. cheers

Thanks for pointing this out. It solved my problem.

**Comment by Aguilar1511** [comment]
@OVagner  Dude ! You really saved me some valuable hours.
Thanks for posting this solution
