### ISSUE TITLE
Unable to generate app with NodeJS 4

### ISSUE THREAD

**Issue by sovattha** [meanjs/generator-meanjs#140]
Hi,

I tried to generate an empty app using `yo meanjs`.
I tried on my Windows 8.1 using Git Bash, then using my Debian 7 installation.
I tried with different options (master/0.4.0/0.41, with CRUD, without, etc.)

This is what the ouput looks like:

```
sso@GIT01:~$ yo meanjs
undefined
You're using the official MEAN.JS generator.
? What mean.js version would you like to generate? master
master
? In which folder would you like the project to be generated? This can be changed later. mean
Cloning the MEAN repo.......
? What would you like to call your application? MEAN
? How would you describe your application? Full-Stack JavaScript with MongoDB, Express, AngularJS, and Node.js
? How would you describe your application in comma seperated key words? MongoDB, Express, AngularJS, Node.js
? What is your company/author name?
? Would you like to generate the article example CRUD module? No
? Would you like to generate the chat example module? No
   create mean/package.json
   create mean/bower.json
   create mean/config/env/default.js
Running npm install for you....
This may take a couple minutes.
Error: Command failed: /bin/sh -c cd mean && npm install
npm WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"4.2.1","npm":"3.3.9"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.2.1","npm":"3.3.9"})
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN install Couldn't install optional dependency: Unsupported
npm WARN prefer global jshint@2.8.0 should be installed with -g
npm WARN prefer global node-gyp@3.0.3 should be installed with -g
npm WARN prefer global nodemon@1.3.8 should be installed with -g
npm WARN prefer global node-inspector@0.10.2 should be installed with -g
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:78:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:93:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sso/mean/node_modules/kerberos
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:kerberos@0.0.16 kerberos@0.0.16 install: `node-gyp rebuild`
npm WARN install:kerberos@0.0.16 Exit status 1
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:78:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:93:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sso/mean/node_modules/bufferutil
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:78:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:93:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sso/mean/node_modules/node-inspector/node_modules/bufferutil
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:bufferutil@1.1.0 bufferutil@1.1.0 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.1.0 Exit status 1
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:78:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:93:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sso/mean/node_modules/node-inspector/node_modules/utf-8-validate
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:utf-8-validate@1.1.0 utf-8-validate@1.1.0 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.1.0 Exit status 1
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:78:19)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:82:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:93:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/sso/mean/node_modules/utf-8-validate
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
npm WARN install:utf-8-validate@1.2.1 Exit status 1
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/home/sso/mean/node_modules/which/which.js:40:28)
gyp ERR! stack     at E (/home/sso/mean/node_modules/which/which.js:43:29)
gyp ERR! stack     at /home/sso/mean/node_modules/which/which.js:54:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/bin/nodejs" "/home/sso/mean/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/sso/mean/node_modules/v8-debug/build/debug/v0.4.6/node-v46-linux-x64/debug.node" "--module_name=debug" "--module_path=/home/sso/mean/node_modules/v8-debug/build/debug/v0.4.6/node-v46-linux-x64"
gyp ERR! cwd /home/sso/mean/node_modules/v8-debug
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/nodejs /home/sso/mean/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/sso/mean/node_modules/v8-debug/build/debug/v0.4.6/node-v46-linux-x64/debug.node --module_name=debug --module_path=/home/sso/mean/node_modules/v8-debug/build/debug/v0.4.6/node-v46-linux-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/sso/mean/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 3.16.0-4-amd64
node-pre-gyp ERR! command "/usr/bin/nodejs" "/home/sso/mean/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/sso/mean/node_modules/v8-debug
node-pre-gyp ERR! node -v v4.2.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.13
node-pre-gyp ERR! not ok
npm WARN EPACKAGEJSON mean@0.0.0 No repository field.
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.9
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/sso/mean/npm-debug.log

    at ChildProcess.exithandler (child_process.js:203:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

Any help would be appreciated. Thanks!

**Comment by codydaig** [comment]
@sovattha We don't fully support Node 4 yet. Sorry. :(

**Comment by sovattha** [comment]
Ok, thank you but what's a working configuration?
If I install a Debian with NodeJS 0.10, would it work?

**Comment by codydaig** [comment]
0.10 or 0.12 and it should work.
