### ISSUE TITLE
Endless Hang on 'Running npm install for you.... This may take a couple minutes.'

### ISSUE THREAD

**Issue by Syferus** [meanjs/generator-meanjs#151]
Running Ubuntu 14.0.4, Node 0.12.8 and NPM 

Everything goes swimmingly until I try to scaffold out the app and get

 'Running npm install for you....
This may take a couple minutes.'

Is this an issue with permissions? If so, how can I fix it?

**Comment by codydaig** [comment]
Theres an update waiting too be published. Once its published, it should work.

**Comment by Syferus** [comment]
Thanks Cody - all the work you do on MeanJS is really appreciated.

**Comment by ilanbiala** [comment]
@codydaig and I have worked to get rid of many of the bugs in 0.4.1, and today we released 0.4.2. Please try it out and if it resolves your issues, let us know!

**Comment by artatro** [comment]
I am still experiencing this problem

**Comment by ilanbiala** [comment]
@codydaig any ideas? I'm not sure what it is.

**Comment by codydaig** [comment]
@artatro What OS are you using? Node Version? NPM Version? What version are you trying to generate of MEAN.JS?

**Comment by mattbodman** [comment]
@Syferus This happened to me to, but when I waited a REALLY long time (10mins+), it worked eventually.  (Mac El Capitan, Node v4.2.2, NPM v3.5.2 trying to generate MeanJS 4.0.0)

**Comment by krissm** [comment]
I have the same problem on windows 10, node 4.2.1, npm 3.5.3.

**Comment by ilanbiala** [comment]
How long does it take to just run `npm install` after deleting `node_modules`?

**Comment by krissm** [comment]
it only happens when I try to generate the meanjs stack using the yo generator. When I clone the meanjs git repository npm install works fine.

**Comment by Megaverse** [comment]
Experiencing same problem with Node 0.12.3, NPM 2.9.1 and I've tried with meanjs versions 4.0.0, 4.0.1 and 4.0.2.

**Comment by sandy-01** [comment]
@codydaig plz giv me the solution of meanJS "running npm install for you this may take couple of minute" i am waiting from last 3 hours but not getting any result

**Comment by codydaig** [comment]
@krissm Try running the generator with `--skip-install`. See if that works. Then run `npm install` afterwards. Otherwise, I'm not entirely sure why it's happening. It seems to be a weird dev env bug.

**Comment by sandy-01** [comment]
Hope so codydaig I will try thnks and get back to u

**Comment by sandy-01** [comment]
Codydaig plz reply me

**Comment by codydaig** [comment]
@sandy-01 Try that potential solution I posted and see if that works.

**Comment by sandy-01** [comment]
@codydiag when I yo meanjs in command promp it still show here"running npm install for you this may take couple of minute

**Comment by ilanbiala** [comment]
do `yo meanjs --skip-install`

**Comment by ilanbiala** [comment]
0.4.3 has been published, please try to see if the new version fixes your issue.

**Comment by gitname** [comment]
I observed this today in Linux. It was on a virtual machine (i.e. Vagrant box) running 64-bit Ubuntu 14.04.4 LTS. 

**I eventually got it working, though, by running `$ yo meanjs --skip-install`, navigating to the app's directory, and running `$ sudo npm install` (i.e. with `sudo`).**

Below is some information about my environment, the things I tried, and the things I observed.

---

Here's some information about my environment:
* User (per `$ whoami`): vagrant
* OS (per `$ lsb_release -a`): Ubuntu 14.04.4 LTS
* Git (per `$ git --version`): 1.9.1
* Node (per `$ node --version`): 4.4.4
* NPM (per `$ npm --version`): 3.9.2
* MongoDB (per `$ mongod --version`): 3.0.12
* Bower (per `$ bower --version`): 1.7.9
* Grunt (grunt-cli) (per `$ grunt --version`): 1.2.0

Below are the things I tried and the things I observed:

---

####  1. `$ yo meanjs` fails :boom: 

I ran `$ yo meanjs` in an attempt to create an app named "mean1." I chose `mean.js` version `0.4.2`. Here's what happened:

```bash
$ yo meanjs
You're using the official MEAN.JS generator.
? What mean.js version would you like to generate? 0.4.2
0.4.2
? In which folder would you like the project to be generated? This can be changed later. mean1
Cloning the MEAN repo.......
? What would you like to call your application? MEAN1
? How would you describe your application? MyDescription
? How would you describe your application in comma seperated key words? Key, Word
? What is your company/author name? John Doe
? Would you like to generate the article example CRUD module? No
? Would you like to generate the chat example module? No
Running npm install for you....
This may take a couple minutes.
Error: Command failed: /bin/sh -c cd mean1 && npm install
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
Killed

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
$
```

Note: The output says "Killed," although I didn't kill it.

---

#### 2.  `$ yo meanjs --skip-install` succeeds :white_check_mark:, but subsequent `$ npm install` fails :boom: 

I ran `$ yo meanjs  --skip-install` as recommend by @codydaig above, in an attempt to create an app named "mean2." I again chose `mean.js` version `0.4.2`. Then, I navigated into the newly-created app directory and ran `$ npm install`. Here's what happened:

```bash
$ yo meanjs --skip-install
You're using the official MEAN.JS generator.
? What mean.js version would you like to generate? 0.4.2
0.4.2
? In which folder would you like the project to be generated? This can be changed later. mean2
Cloning the MEAN repo.......
? What would you like to call your application? MEAN
? How would you describe your application? Full-Stack JavaScript with MongoDB, Express, AngularJS, and Node.js
? How would you describe your application in comma seperated key words? MongoDB, Express, AngularJS, Node.js
? What is your company/author name?
? Would you like to generate the article example CRUD module? No
? Would you like to generate the chat example module? No
$ cd mean2
$ npm install
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
extract:validator → gunzT ▀ ╢█████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
Killed
$
```

Note: The output (of `$ npm install`) says "Killed," although I didn't kill it.

---

#### 3.  `$ yo meanjs --skip-install` succeeds :white_check_mark:, and subsequent `$ sudo npm install` succeeds :white_check_mark:

I again ran `$ yo meanjs  --skip-install`, this time in an attempt to create an app named "mean3." I again chose `mean.js` version `0.4.2`. Then, I navigated into the newly-created app directory and ran `$ sudo npm install` (i.e. with `sudo` this time). Here's what happened:

```bash
$ yo meanjs --skip-install
You're using the official MEAN.JS generator.
? What mean.js version would you like to generate? 0.4.2
0.4.2
? In which folder would you like the project to be generated? This can be changed later. mean3
Cloning the MEAN repo.......
? What would you like to call your application? MEAN
? How would you describe your application? Full-Stack JavaScript with MongoDB, Express, AngularJS, and Node.js
? How would you describe your application in comma seperated key words? MongoDB, Express, AngularJS, Node.js
? What is your company/author name?
? Would you like to generate the article example CRUD module? No
? Would you like to generate the chat example module? No
$ cd mean3
$ sudo npm install
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
extract:validator → gunzT ▌ ╢█████████████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
$
```
Note: No mention of any processes being "Killed" this time.
