### ISSUE TITLE
Error: Command failed

### ISSUE THREAD

**Issue by EliasJorgensen** [meanjs/generator-meanjs#178]
Hi,
I'm trying to use the meanjs generator, but when i hit the step "Running npm install for you...", i get this:
```
Running npm install for you....
This may take a couple minutes.
Error: Command failed: /bin/sh -c cd mean && npm install
npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"4.2.4","npm":"3.5.2"})
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
Killed

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

```

I'm using Node v4.2.4 and npm v3.5.2.
It happens when i try to generate MeanJS 0.4.0, 0.4.1 and 0.4.2

**Comment by ilanbiala** [comment]
You get the same message when generating all 3 versions?

**Comment by EliasJorgensen** [comment]
I do, it's very strange...

**Comment by EliasJorgensen** [comment]
<b>EDIT</b>: I get another error when i generate 0.4.1 and 0.4.2
```
Error: Command failed: /bin/sh -c cd mean && npm install
npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"4.2.4","npm":"3.5.2"})
npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
npm ERR! Linux 3.13.0-74-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.4
npm ERR! npm  v3.5.2

npm ERR! Invalid array buffer length
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagrant/mean/npm-debug.log

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

```
I got the error from my original post when generating 0.4.0.
I'm using an ubuntu/trusty64 vagrant box.

**Comment by ilanbiala** [comment]
Can you try with npm 2.x.x?

**Comment by EliasJorgensen** [comment]
I downgraded to npm v2.14.14 and tried to run the generator for each version.
Here's a paste of my terminal: http://pastebin.com/XgSGA9wq

**Comment by ilanbiala** [comment]
Are the folders empty? Is there an error log file in the directory or somewhere?

**Comment by EliasJorgensen** [comment]
The folders aren't empty. Here's the content of them:
```
vagrant@meeseeks:~$ ls mean
bower.json    config           docker-compose.yml  gruntfile.js  karma.conf.js  manifest.yml  node_modules  Procfile            public     scripts    test.js
CHANGELOG.md  CONTRIBUTING.md  Dockerfile          gulpfile.js   LICENSE.md     modules       package.json  protractor.conf.js  README.md  server.js
vagrant@meeseeks:~$ ls mean1
bower.json  CONTRIBUTING.md     Dockerfile    gulpfile.js    LICENSE.md    modules       package.json  protractor.conf.js  README.md  server.js
config      docker-compose.yml  gruntfile.js  karma.conf.js  manifest.yml  node_modules  Procfile      public              scripts    test.js
vagrant@meeseeks:~$ ls mean2
bower.json  config  docker-compose.yml  Dockerfile  gruntfile.js  gulpfile.js  karma.conf.js  LICENSE.md  modules  node_modules  package.json  Procfile  protractor.conf.js  public  README.md  scripts  server.js
vagrant@meeseeks:~$ 
```
The folder "mean" is 0.4.2, "mean1" is 0.4.1 and "mean2" is 0.4.0.
As far as i can see, there isn't any error logs in the directories or in my home folder, where i ran the generator from.

**Comment by ilanbiala** [comment]
0.4.3 has been published, please try to see if the new version fixes your issue.

**Comment by rengas** [comment]
I had the same issue trying to run to yo generator on box with vagrant.Increasing base memory of the box size fixed it.
