### ISSUE TITLE
Can't generate meanjs project.

### ISSUE THREAD

**Issue by antares667367** [meanjs/generator-meanjs#197]
For a reason i completely dont get , this is what displays on my term while trying to generate a meanjs project.

For the record i'm behind a corporate proxy , i've managed to make npm ,bower , ruby and sass connecting outside but so far no luck with the generator.
Maybe i did something wrong but i merely followed the instructions.

i've used this tutorial :
https://github.com/meanjs/mean

**D:\forks\x**
$>> yo meanjs                                                                                                                
**You're using the official MEAN.JS generator.   **                                                                            
? What mean.js version would you like to generate? 0.4.2                                                                   
0.4.2                                                                                                                      
? In which folder would you like the project to be generated? This can be changed later. **app **                              
Cloning the MEAN repo.......                                                                                               
# Error: Command failed: C:\Windows\system32\cmd.exe /s /c "git clone --branch v0.4.2 https://github.com/meanjs/mean.git app"
**Cloning into 'app'...  **                                                                                                    
fatal: unable to access 'https://github.com/meanjs/mean.git/': Couldn't resolve host 'github.com'   

additionnal information you might wan't to see;

D:\forks\x
λ node -v             
v5.3.0                
                      
D:\forks\x
λ npm -v              
3.3.12

**Comment by antares667367** [comment]
Sorry , it seems my question is a duplicate from a previous topic .

And to answer the question asked in that duplicate :

D:\forks\x                                                                           
λ ## git clone --branch v0.4.2 https://github.com/meanjs/mean.git app                               
Cloning into 'app'...                                                                            
## fatal: unable to access 'https://github.com/meanjs/mean.git/': Couldn't resolve host 'github.com'

executing the commant between the quotes does not work either.

**Comment by ilanbiala** [comment]
It seems like you can't git clone from github. That probably has something to do with the proxy. Try cloning from another URL and see if that works.

**Comment by antares667367** [comment]
Well, thanks a lot for the quick response mate.
I kinda «fixed» my problem in fact.
I've dl the zip file and unzipped it in the appropriate rep.
I had to use --force with grunt though for elint caused me some problems
too, the indentation of the gruntfile seems quite messed up !

Once started, the page is blank, wasnt i supposed to have a least a welcome
page as in the video tutorial ? , (the one with the x-mens).

Thank again, i'll keep you posted in case a find a workaround concerning
the generator.
If it works a home with identical conditions without  the proxy, i'll have
solved part of the mystery.

Thomas.

**Comment by alexkempf** [comment]
@antares667367, I had a similar issue (also behind a corporate proxy). For me, I needed to add a few gitconfig settings.
```bash
[http]
	sslVerify = false
[url "https://"]
	insteadOf = git://
```

I am not sure if they were both necessary or if they will even work for you, but they did the trick for me.

**Comment by antares667367** [comment]
I'll give a try.

Thanks

**Comment by antares667367** [comment]
ok , that was the proxy blocking my connection, now i've got another problem.

`    Fri, 12 Feb 2016 20:35:13 GMT body-parser deprecated undefined extended: provide extended option at co
nfig\express.js:57:24
    Fri, 12 Feb 2016 20:35:13 GMT express-session deprecated undefined resave option; provide resave optio
n at config\express.js:62:13
    Fri, 12 Feb 2016 20:35:13 GMT express-session deprecated undefined saveUninitialized option; provide s
aveUninitialized option at config\express.js:62:13
    static-icon deprecated; switch to module serve-favicon
    Express app started on port 3000
    Unhandled rejection MongoError: cannot connect to server
        at Collection.listIndexes (C:\Users\antares\Desktop\mean001\node_modules\mongoose\node_modules\mon
godb\lib\collection.js:1732:11)
        at indexInformation (C:\Users\antares\Desktop\mean001\node_modules\mongoose\node_modules\mongodb\l
ib\db.js:1607:25)
        at Db.indexInformation (C:\Users\antares\Desktop\mean001\node_modules\mongoose\node_modules\mongod
b\lib\db.js:1571:44)
        at ensureIndex (C:\Users\antares\Desktop\mean001\node_modules\mongoose\node_modules\mongodb\lib\db
.js:1066:8)
        at Db.ensureIndex (C:\Users\antares\Desktop\mean001\node_modules\mongoose\node_modules\mongodb\lib
\db.js:1042:44)
        at ensureIndex (C:\Users\antares\Desktop\mean001\node_modules\mongoose\node_modules\mongodb\lib\co
llection.js:1802:13)
        at Collection.ensureIndex (C:\Users\antares\Desktop\mean001\node_modules\mongoose\node_modules\mon
godb\lib\collection.js:1790:44)
        at MongoStore.setAutoRemoveAsync (C:\Users\antares\Desktop\mean001\node_modules\connect-mongo\src\
index.js:123:40)
        at MongoStore.handleNewConnectionAsync (C:\Users\antares\Desktop\mean001\node_modules\connect-mong
o\src\index.js:116:18)
        at MongoStore (C:\Users\antares\Desktop\mean001\node_modules\connect-mongo\src\index.js:95:26)
        at module.exports (C:\Users\antares\Desktop\mean001\config\express.js:64:16)
        at Object.<anonymous> (C:\Users\antares\Desktop\mean001\server.js:39:28)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Function.Module.runMain (module.js:447:10)
        at startup (node.js:139:18)
        at node.js:999:3`

Obviously the base cannot be reached/found for some reason.
I have absolutely no idea where i am suppose to find or set the databasename so it can match with mongo since i am a total newbie and the structure is far more complex than i have anticipated.

Any idea or suggestions ?

**Comment by ilanbiala** [comment]
@antares667367 I can't really read the error message, can you paste it in a gist or something that is more clear? From a cursory look, take a look at config\express.js:62:13 and at some of the Connect-Mongo packages.

**Comment by graphpixel** [comment]
I am still confused here. Did anyone solve the problem?
