### ISSUE TITLE
Yo cannot be ran as root or using sudo

### ISSUE THREAD

**Issue by orenyny** [meanjs/generator-meanjs#226]
Hello,
I hope this is the right place to ask you to correct the documentation. In this page - http://meanjs.org/generator.html you explain that super user or sudo may be needed to do the installation.
There is a major issue using yo as root or using sudo. I followed their suggestions here https://github.com/yeoman/yeoman.github.io/issues/282, switching between root and a user, with no success. 
Here are the errors about deprecated packages which eventually fails the process:

Running npm install for you....
This may take a couple minutes.
Error: Command failed: cd meanjs && npm install
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated cross-spawn-async@2.2.4: cross-spawn no longer requires a build toolchain, use it instead!
Killed

    at ChildProcess.exithandler (child_process.js:207:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

**Comment by codydaig** [comment]
Those are errors about deprecated packages. The Killed at the end is the only issue here. Typically that means that you ran out of memory or something. Are you trying to do this on a VM?
