### ISSUE TITLE
Unable to generate meanjs using yeoman generator

### ISSUE THREAD

**Issue by mukul273** [meanjs/generator-meanjs#244]
I am build the first ever project for MEAN on windows 7

So I have installed Node, Grunt, bower, npm, yo...

C:\codesnippet\src>node --version
v4.4.7

C:\MEAN\codesnippet\src>npm --version
2.15.8

C:\codesnippet\src>yo --version
1.8.4

C:\codesnippet\src>bower --version
1.7.9

I am getting errors like these..Can anybody help?

C:\CodeSnippet>yo meanjs
You're using the official MEAN.JS generator.
? What mean.js version would you like to generate? 0.4.0
0.4.0
? In which folder would you like the project to be generated? This can be changed later. mean
Cloning the MEAN repo.......
? What would you like to call your application? CodeSnippet
? How would you describe your application? Code Share
? How would you describe your application in comma seperated key words? Code Snippet
? What is your company/author name? Test
? Would you like to generate the article example CRUD module? No
? Would you like to generate the chat example module? No
Running npm install for you....
This may take a couple minutes.
Error: Command failed: C:\windows\system32\cmd.exe /s /c "cd mean && npm install"
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm WARN engine karma@0.12.37: wanted: {"node":">=0.8 <=0.12 || >=1 <=2"} (current: {"node":"4.4.7","npm":"2.15.8"})
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in
 the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in
 the tree.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN optional dep failed, continuing fsevents@1.0.14
npm WARN peerDependencies The peer dependency kerberos@~0.0 included from mongodb-core will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:356:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\CodeSnippet\mean\node_modules\connect-mongo\node_modules\mongodb\node_modules\kerberos
gyp ERR! node -v v4.4.7
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

**Comment by ilanbiala** [comment]
@mukul273 have you tried installing Python?

**Comment by littlerkap** [comment]
I'm also facing the same issue.
Atteched log file:
[npm-debug.txt](https://github.com/meanjs/generator-meanjs/files/675922/npm-debug.copy.txt)
