### ISSUE TITLE
Unable to use sub-generator

### ISSUE THREAD

**Issue by mikeroskywalker** [meanjs/generator-meanjs#249]
I was not able to run the sub-generator:

`yo meanjs:express-model <model-name>`

It prompts the question, and I was unable to see any controller name. And I was running in the root directory of my project. I tried this in Mac/Linux(Ubuntu)/Windows7

`? Which module does this controller belongs to?`

**Comment by ilanbiala** [comment]
@mikeroskywalker can you post the terminal output?

**Comment by mikeroskywalker** [comment]
@ilanbiala 

`$ yo meanjs:express-model test
? Which module does this controller belongs to? 


readline.js:930
            throw err;
            ^

TypeError: Cannot read property 'value' of undefined
    at Prompt.getCurrentValue (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/prompts/list.js:123:51)
    at tryCatcher (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:63:31)
    at InnerObserver.next (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:5407:43)
    at InnerObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1762:31)
    at InnerObserver.tryCatcher (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:63:31)
    at AutoDetachObserverPrototype.next (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:5883:51)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1762:31)
    at TakeObserver.next (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:5646:17)
    at TakeObserver.Rx.internals.AbstractObserver.AbstractObserver.onNext (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:1762:31)
    at TakeObserver.tryCatcher (/usr/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/node_modules/rx/dist/rx.js:63:31)
`

I was asked to use  arrow key to choose the module but I was not able see anything on the terminal.

**Comment by ilanbiala** [comment]
@mikeroskywalker which version of the generator are you using? Have you tried just running the standard generator?

**Comment by UCDaHacker** [comment]
I have that exact same issue. Looks like the new yeoman generates into a new directory structure. What's the standard generator?
